config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  namespace :admin do
    resources :pets, only: [:index]
  end

  namespace :user do
    scope '/:user_id' do
      resources :pets, only: [:create, :index, :new]
      resources :allergy_records, only: [:create, :new]
      resources :allergy_reactions, only: [:create, :new]
      resources :vaccine_records, only: [:create, :new]
    end
  end
end

app/models/allergy_reaction.rb
# frozen_string_literal: true

class AllergyReaction < ApplicationRecord
  validates :allergy_record_id, :reaction, :severity, presence: true
  enum severity: {
    mild: 0,
    moderate: 1,
    severe: 2
  }

  enum reaction: {
    facial_swelling: 0,
    hives: 1,
    itchy_skin: 2,
    respiratory_distress: 3,
    vommiting: 4
  }

  belongs_to :allergy_record
end

app/models/allergy_record.rb
# frozen_string_literal: true

class AllergyRecord < MedicalRecord
  belongs_to :pet
  has_many :allergy_reactions
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/medical_record.rb
# frozen_string_literal: true

class MedicalRecord < ApplicationRecord
  self.abstract_class = true
  validates :name, :pet_id, presence: true
end

app/models/pet.rb
# frozen_string_literal: true

class Pet < ApplicationRecord
  validates :name, :species, :owner_first, :owner_last, :date_of_birth, presence: true
  validates :name, uniqueness: { scope: %i[species owner_first owner_last date_of_birth] }
  enum species: {
    bird: 0,
    cat: 1,
    chicken: 2,
    dog: 3,
    ferret: 4,
    fish: 5,
    guinea_pig: 6,
    hampster: 7,
    rabbit: 8,
    reptile: 9
  }

  has_many :vaccine_records, dependent: :destroy
  has_many :allergy_records, dependent: :destroy

  def has_overdue_vaccines
    VaccineRecord.where(pet_id: id).where('date_administered < ?', Date.today - 365).count.positive?
  end
end

app/models/vaccine_record.rb
# frozen_string_literal: true

class VaccineRecord < MedicalRecord
  validates :date_administered, presence: true

  belongs_to :pet
end

app/controllers/admin/pets_controller.rb
# frozen_string_literal: true

module Admin
  class PetsController < ApplicationController
    def index
      @pets = Pet.all.order(:name)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/user/allergy_reactions_controller.rb
# frozen_string_literal: true

module User
  class AllergyReactionsController < ApplicationController
    def create
      @allergy_reaction = AllergyReaction.new(allergy_reaction_params)
      @allergy_record = AllergyRecord.find(@allergy_reaction.allergy_record_id)
      @pet = Pet.find(@allergy_record.pet_id)
      if @allergy_reaction.save
        redirect_to "/user/#{params[:user_id]}/allergy_reactions/new?allergy_record_id=#{@allergy_record.id}"
      else
        render :new, status: :unprocessable_entity
      end
    end

    def new
      @allergy_record = AllergyRecord.find(params[:allergy_record_id])
      @pet = Pet.find(@allergy_record.pet_id)
      @user_id = params[:user_id]
      @allergy_reaction = AllergyReaction.new(allergy_record_id: @allergy_record.id)
    end

    private

    def allergy_reaction_params
      params.require(:allergy_reaction).permit(:user_id, :allergy_record_id, :reaction, :severity)
    end
  end
end

app/controllers/user/allergy_records_controller.rb
# frozen_string_literal: true

module User
  class AllergyRecordsController < ApplicationController
    def create
      @allergy_record = AllergyRecord.new(allergy_record_params)
      @pet = Pet.find(@allergy_record.pet_id)
      if @allergy_record.save
        redirect_to new_user_allergy_reaction_path(allergy_record_id: @allergy_record.id)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def new
      @pet = Pet.find(params[:pet_id])
      @allergy_record = AllergyRecord.new(pet_id: @pet.id)
    end

    private

    def allergy_record_params
      params.require(:allergy_record).permit(:id, :name, :date_administered, :pet_id)
    end
  end
end

app/controllers/user/pets_controller.rb
# frozen_string_literal: true

module User
  class PetsController < ApplicationController
    def create
      pet_params_with_created_by = pet_params.to_h.merge({ created_by: params[:user_id] })
      @pet = Pet.new(pet_params_with_created_by)
      if @pet.save
        redirect_to user_pets_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    def index
      @user_id = params[:user_id]
      @pets = Pet.all.where(created_by: @user_id).order(:name)
    end

    def new
      @pet = Pet.new
    end

    def show
      pet = Pet.find(params[:id])
      render json: pet
    end

    private

    def pet_params
      params.require(:pet).permit(:name, :species, :owner_first, :owner_last, :date_of_birth, :created_by)
    end
  end
end

app/controllers/user/vaccine_records_controller.rb
# frozen_string_literal: true

module User
  class VaccineRecordsController < ApplicationController
    def create
      @vaccine_record = VaccineRecord.new(vaccine_record_params)
      @pet = Pet.find(@vaccine_record.pet_id)
      if @vaccine_record.save
        redirect_to user_pets_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    def new
      @pet = Pet.find(params[:pet_id])
      @vaccine_record = VaccineRecord.new(pet_id: @pet.id)
    end

    private

    def vaccine_record_params
      params.require(:vaccine_record).permit(:name, :date_administered, :pet_id)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/admin/pets/index.html.erb
<h1> Novellia for Pets </h1>

<style>
  table {
    width: 100%;
    border-collapse: collapse;
  }
  th, td {
    border: 1px solid black;
    text-align: center;
    padding: 8px;
  }
</style>

<style>
  .right-align {
    text-align: right;
  }
</style>

<br>
<table id="pets-list" >
    <thead>
        <tr>
        <th>Pet Name</th>
        <th>Species</th>
        <th>Owner Name</th>
        <th>DOB</th>
        <th>Medical Records</th>
        </tr>
    </thead>
    <tbody>
        <% @pets.each do |pet| %>
        <tr id="pet-id-<%=pet.id%>" style="<%= 'background-color: #ffcccc;' if pet.has_overdue_vaccines %>">
            <td><%= pet.name %></td>
            <td><%= pet.species %></td>
            <td><%= pet.owner_first %> <%= pet.owner_last %></td>
            <td><%= pet.date_of_birth %></td>
            <td> 
                <strong>Vaccines:</strong> <br>
                <table>
                    <thead>
                        <tr>
                            <th>Vaccine Name</th>
                            <th>Date Administered</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% if pet.vaccine_records.empty? %>
                            <tr>
                                <td colspan="2">No vaccine records found for this pet.</td>
                            </tr>
                        <% else %>
                            <% pet.vaccine_records.each do |vaccine_record|  %>
                            <tr>
                                <td><%= vaccine_record.name %></td>
                                <td><%= vaccine_record.date_administered %></td>
                            </tr>
                            <% end %>
                        <% end %>
                </table>
                <br>
                <br> <strong>Allergies:</strong> <br>
                <table>
                    <thead>
                        <tr>
                            <th>Allergen</th>
                            <th>Reactions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% if pet.allergy_records.empty? %>
                            <tr>
                                <td colspan="2">No allergy records found for this pet.</td>
                            </tr>
                        <% else %>
                            <% pet.allergy_records.each do |allergy_record|  %>
                            <tr>
                                <td><%= allergy_record.name %></td>
                                <td>
                                    <% allergy_record.allergy_reactions.each do |allergy_reaction|  %>
                                        <%= allergy_reaction.reaction %> -
                                        <%= allergy_reaction.severity %> <br> 
                                    <% end %>
                                </td>
                            </tr>
                            <% end %>
                        <% end %>
                    </tbody>
                </table>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/allergy_reactions/new.html.erb
<style>
  .right-align {
    text-align: right;
  }
</style>

<div class="right-align">
  <%= button_to 'All Pets', '/', method: :get %>
</div>

<h1><%=  @allergy_record.name %> Allergy Record for <%= @pet.name %></h1>

<h2> Reactions </h2>
<% if @allergy_record.allergy_reactions.any? %>
    <ul>
        <% @allergy_record.allergy_reactions.each do |reaction| %>
            <li><%= reaction.reaction %> - <%= reaction.severity %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @allergy_reaction do |form| %>
    <% if @allergy_reaction&.errors&.any? %>
        <div id="error_explanation"  style="color: red;">
            <h4><%= pluralize(@allergy_reaction.errors.count, "error") %> prohibited this allergy record from being saved:</h4>

            <ul>
            <% @allergy_reaction.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
            </ul>
            <br><br>
        </div>
    <% end %>
    <h3>New Allergy Reaction for <%= @pet&.name %>'s <%= @allergy_record&.name %> Allergy</h3>
        <div class="field">
        <%= form.label :reaction %><br>
        <%= form.select :reaction, AllergyReaction.reactions.keys.map { |s| [s.humanize, s] } %>
        </div>

        <div class="field">
        <%= form.label :severity %><br>
        <%= form.select :severity, AllergyReaction.severities.keys.map { |s| [s.humanize, s] } %>
        </div>

        <%= form.hidden_field :allergy_record_id, value: @allergy_record.id %>

    <div class="actions">
    <%= form.submit 'Add Allergy Reaction'%>
    </div>
<% end %>

app/views/allergy_records/new.html.erb
<%= form_for @allergy_record do |form| %>
    <% if @allergy_record&.errors&.any? %>
        <div id="error_explanation"  style="color: red;">
            <h4><%= pluralize(@allergy_record.errors.count, "error") %> prohibited this allergy record from being saved:</h4>

            <ul>
            <% @allergy_record.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
            </ul>
            <br><br>
        </div>
    <% end %>
    <h3>New Allergy Record for <%= @pet&.name %> </h3>
    <%= form.label :name, 'Allergy Name:' %>
    <%= form.text_field :name %><br>
    
    <%= form.hidden_field :pet_id, value: @pet.id %>

    <div class="actions">
    <%= form.submit 'Add Allergy Record'%>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NovelliaPets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/index.html.erb
<h1> Novellia for Pets </h1>

<style>
  table {
    width: 100%;
    border-collapse: collapse;
  }
  th, td {
    border: 1px solid black;
    text-align: center;
    padding: 8px;
  }
</style>

<style>
  .right-align {
    text-align: right;
  }
</style>

<div class="right-align">
  <%= button_to 'Add a Pet', 'pets/new', method: :get %>
</div>
<br>
<table id="pets-list" >
    <thead>
        <tr>
        <th>Pet Name</th>
        <th>Species</th>
        <th>Owner Name</th>
        <th>DOB</th>
        <th>Medical Records</th>
        </tr>
    </thead>
    <tbody>
        <% @pets.each do |pet| %>
        <tr id="pet-id-<%=pet.id%>">
            <td><%= pet.name %></td>
            <td><%= pet.species %></td>
            <td><%= pet.owner_first %> <%= pet.owner_last %></td>
            <td><%= pet.date_of_birth %></td>
            <td> 
                <div class="right-align">
                  <%= button_to 'Add Vaccine Record', new_vaccine_record_path(pet.id), method: :get %>
                </div>
                <strong>Vaccines:</strong> <br>
                <table>
                    <thead>
                        <tr>
                            <th>Vaccine Name</th>
                            <th>Date Administered</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% if pet.vaccine_records.empty? %>
                            <tr>
                                <td colspan="2">No vaccine records found for this pet.</td>
                            </tr>
                        <% else %>
                            <% pet.vaccine_records.each do |vaccine_record|  %>
                            <tr>
                                <td><%= vaccine_record.name %></td>
                                <td><%= vaccine_record.date_administered %></td>
                            </tr>
                            <% end %>
                        <% end %>
                </table>
                <br>
                <div class="right-align">
                    <%= button_to 'Add Allergy Record', new_allergy_record_path(pet.id), method: :get %>
                </div>
                <br> <strong>Allergies:</strong> <br>
                <table>
                    <thead>
                        <tr>
                            <th>Allergen</th>
                            <th>Reactions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% if pet.allergy_records.empty? %>
                            <tr>
                                <td colspan="2">No allergy records found for this pet.</td>
                            </tr>
                        <% else %>
                            <% pet.allergy_records.each do |allergy_record|  %>
                            <tr>
                                <td><%= allergy_record.name %></td>
                                <td>
                                    <% allergy_record.allergy_reactions.each do |allergy_reaction|  %>
                                        <%= allergy_reaction.reaction %> -
                                        <%= allergy_reaction.severity %> <br> 
                                    <% end %>
                                    <%= button_to 'Add Reaction', new_allergy_reaction_path(allergy_record.id), method: :get %>
                                </td>
                            </tr>
                            <% end %>
                        <% end %>
                    </tbody>
                </table>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/pets/new.html.erb
<%= form_for @pet do |form| %>
    <% if @pet&.errors&.any? %>
        <div id="error_explanation"  style="color: red;">
            <h4><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h4>

            <ul>
            <% @pet.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
            </ul>
            <br><br>
        </div>
    <% end %>
    <h3>New Pet </h3>
    <%= form.label :name, 'Pet Name:' %>
    <%= form.text_field :name %><br>
    <div class="field">
    <%= form.label :species %><br>
    <%= form.select :species, Pet.species.keys.map { |s| [s.humanize, s] } %>
    </div>

    <%= form.label :owner_first, 'Owner First Name:' %>
    <%= form.text_field :owner_first %><br>
    <%= form.label :owner_last, 'Owner Last Name:' %>
    <%= form.text_field :owner_last %><br>

    <%= form.label :date_of_birth, 'Pet\'s DOB:' %>
    <%= form.date_select :date_of_birth %><br>

    <div class="actions">
    <%= form.submit 'Add Pet'%>
    </div>
<% end %>

app/views/user/allergy_reactions/new.html.erb
<style>
  .right-align {
    text-align: right;
  }
</style>

<div class="right-align">
  <%= button_to 'All Pets', "/user/#{@user_id}/pets", method: :get %>
</div>

<h1><%=  @allergy_record.name %> Allergy Record for <%= @pet.name %></h1>

<h2> Reactions </h2>
<% if @allergy_record.allergy_reactions.any? %>
    <ul>
        <% @allergy_record.allergy_reactions.each do |reaction| %>
            <li><%= reaction.reaction %> - <%= reaction.severity %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for [:user, @allergy_reaction] do |form| %>
    <% if @allergy_reaction&.errors&.any? %>
        <div id="error_explanation"  style="color: red;">
            <h4><%= pluralize(@allergy_reaction.errors.count, "error") %> prohibited this allergy record from being saved:</h4>

            <ul>
            <% @allergy_reaction.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
            </ul>
            <br><br>
        </div>
    <% end %>
    <h3>New Allergy Reaction for <%= @pet&.name %>'s <%= @allergy_record&.name %> Allergy</h3>
        <div class="field">
        <%= form.label :reaction %><br>
        <%= form.select :reaction, AllergyReaction.reactions.keys.map { |s| [s.humanize, s] } %>
        </div>

        <div class="field">
        <%= form.label :severity %><br>
        <%= form.select :severity, AllergyReaction.severities.keys.map { |s| [s.humanize, s] } %>
        </div>

        <%= form.hidden_field :allergy_record_id, value: @allergy_record.id %>

    <div class="actions">
    <%= form.submit 'Add Allergy Reaction'%>
    </div>
<% end %>

app/views/user/allergy_records/new.html.erb
<%= form_for [:user, @allergy_record] do |form| %>
    <% if @allergy_record&.errors&.any? %>
        <div id="error_explanation"  style="color: red;">
            <h4><%= pluralize(@allergy_record.errors.count, "error") %> prohibited this allergy record from being saved:</h4>

            <ul>
            <% @allergy_record.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
            </ul>
            <br><br>
        </div>
    <% end %>
    <h3>New Allergy Record for <%= @pet&.name %> </h3>
    <%= form.label :name, 'Allergy Name:' %>
    <%= form.text_field :name %><br>
    
    <%= form.hidden_field :pet_id, value: @pet.id %>

    <div class="actions">
    <%= form.submit 'Add Allergy Record'%>
    </div>
<% end %>

app/views/user/pets/index.html.erb
<h1> My Pets </h1>

<style>
  table {
    width: 100%;
    border-collapse: collapse;
  }
  th, td {
    border: 1px solid black;
    text-align: center;
    padding: 8px;
  }
</style>

<style>
  .right-align {
    text-align: right;
  }
</style>

<div class="right-align">
  <%= button_to 'Add a Pet', 'pets/new', method: :get %>
</div>
<br>
<table id="pets-list" >
    <thead>
        <tr>
        <th>Pet Name</th>
        <th>Species</th>
        <th>Owner Name</th>
        <th>DOB</th>
        <th>Medical Records</th>
        </tr>
    </thead>
    <tbody>
        <% @pets.each do |pet| %>
        <tr id="pet-id-<%=pet.id%>" style="<%= 'background-color: #ffcccc;' if pet.has_overdue_vaccines %>">
            <td><%= pet.name %></td>
            <td><%= pet.species %></td>
            <td><%= pet.owner_first %> <%= pet.owner_last %></td>
            <td><%= pet.date_of_birth %></td>
            <td> 
                <div class="right-align">
                  <%= link_to 'Add Vaccine Record', "/user/#{@user_id}/vaccine_records/new?pet_id=#{pet.id}", method: :get %>
                </div>
                <strong>Vaccines:</strong> <br>
                <table>
                    <thead>
                        <tr>
                            <th>Vaccine Name</th>
                            <th>Date Administered</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% if pet.vaccine_records.empty? %>
                            <tr>
                                <td colspan="2">No vaccine records found for this pet.</td>
                            </tr>
                        <% else %>
                            <% pet.vaccine_records.each do |vaccine_record|  %>
                            <tr>
                                <td><%= vaccine_record.name %></td>
                                <td><%= vaccine_record.date_administered %></td>
                            </tr>
                            <% end %>
                        <% end %>
                </table>
                <br>
                <div class="right-align">
                    <%= link_to 'Add Allergy Record', "/user/#{@user_id}/allergy_records/new?pet_id=#{pet.id}" , method: :get %>
                </div>
                <br> <strong>Allergies:</strong> <br>
                <table>
                    <thead>
                        <tr>
                            <th>Allergen</th>
                            <th>Reactions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% if pet.allergy_records.empty? %>
                            <tr>
                                <td colspan="2">No allergy records found for this pet.</td>
                            </tr>
                        <% else %>
                            <% pet.allergy_records.each do |allergy_record|  %>
                            <tr>
                                <td><%= allergy_record.name %></td>
                                <td>
                                    <% allergy_record.allergy_reactions.each do |allergy_reaction|  %>
                                        <%= allergy_reaction.reaction %> -
                                        <%= allergy_reaction.severity %> <br> 
                                    <% end %>
                                    
                                    <%= link_to 'Add Reaction', "/user/#{@user_id}/allergy_reactions/new?allergy_record_id=#{allergy_record.id}", method: :get %>
                                </td>
                            </tr>
                            <% end %>
                        <% end %>
                    </tbody>
                </table>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/user/pets/new.html.erb
<%= form_for [:user, @pet] do |form| %>
    <% if @pet&.errors&.any? %>
        <div id="error_explanation"  style="color: red;">
            <h4><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h4>

            <ul>
            <% @pet.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
            </ul>
            <br><br>
        </div>
    <% end %>
    <h3>New Pet </h3>
    <%= form.label :name, 'Pet Name:' %>
    <%= form.text_field :name %><br>
    <div class="field">
    <%= form.label :species %><br>
    <%= form.select :species, Pet.species.keys.map { |s| [s.humanize, s] } %>
    </div>

    <%= form.label :owner_first, 'Owner First Name:' %>
    <%= form.text_field :owner_first %><br>
    <%= form.label :owner_last, 'Owner Last Name:' %>
    <%= form.text_field :owner_last %><br>

    <%= form.label :date_of_birth, 'Pet\'s DOB:' %>
    <%= form.date_select :date_of_birth %><br>

    <div class="actions">
    <%= form.submit 'Add Pet'%>
    </div>
<% end %>

app/views/user/vaccine_records/new.html.erb
<%= form_for [:user, @vaccine_record] do |form| %>
    <% if @vaccine_record&.errors&.any? %>
        <div id="error_explanation"  style="color: red;">
            <h4><%= pluralize(@vaccine_record.errors.count, "error") %> prohibited this vaccine record from being saved:</h4>

            <ul>
            <% @vaccine_record.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
            </ul>
            <br><br>
        </div>
    <% end %>
    <h3>New Vaccine Record for <%= @pet&.name %> </h3>
    <%= form.label :name, 'Vaccine Name:' %>
    <%= form.text_field :name %><br>
   
    <%= form.label :date_administered, 'Date Administered:' %>
    <%= form.date_select :date_administered %><br>
   
    <%= form.hidden_field :pet_id, value: @pet.id %>

    <div class="actions">
    <%= form.submit 'Add Vaccine Record'%>
    </div>
<% end %>

app/views/vaccine_records/new.html.erb
<%= form_for @vaccine_record do |form| %>
    <% if @vaccine_record&.errors&.any? %>
        <div id="error_explanation"  style="color: red;">
            <h4><%= pluralize(@vaccine_record.errors.count, "error") %> prohibited this vaccine record from being saved:</h4>

            <ul>
            <% @vaccine_record.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
            </ul>
            <br><br>
        </div>
    <% end %>
    <h3>New Vaccine Record for <%= @pet&.name %> </h3>
    <%= form.label :name, 'Vaccine Name:' %>
    <%= form.text_field :name %><br>
   
    <%= form.label :date_administered, 'Date Administered:' %>
    <%= form.date_select :date_administered %><br>
   
    <%= form.hidden_field :pet_id, value: @pet.id %>

    <div class="actions">
    <%= form.submit 'Add Vaccine Record'%>
    </div>
<% end %>